# Generated by Django 2.0.6 on 2018-08-10 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manytomanyapp', '0002_auto_20180810_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relation',
            old_name='sub',
            new_name='subject',
        ),
    ]
