# Generated by Django 2.0.6 on 2018-08-09 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('job', models.CharField(max_length=20)),
                ('salary', models.FloatField()),
            ],
        ),
    ]
