# Generated by Django 2.0.6 on 2018-08-17 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworkapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='qq',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
