# Generated by Django 2.0.6 on 2018-08-09 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schname', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuname', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=10)),
                ('score', models.FloatField()),
                ('stuschool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onetomanyapp.School')),
            ],
        ),
    ]
